- hosts: all
  ignore_unreachable: False
  gather_facts: yes
  vars:
    - rebt: "{{ reboot_now | default('false') }}"
    - chc_pres: "{{ choco_presence | default('false') }}"
  tasks:
    - debug:
        msg: "{{ chc_pres }}"

    - name: update packages from internal
      become: no
      win_chocolatey:
       name: all
       state: latest
       source: 'https://chocolately.org/api/v2/'
      #  source: https://iis_host1.cforat.org/chocolatey
      when:
        - ansible_facts['os_family'] == "Windows"
        - chc_pres == true
    - name: updates
      block:
        - name: Run Install Task
          become: no
          win_updates:
            category_names:
              - "Critical Updates"
              - "CriticalUpdates"
              - "Feature Packs"
              - "Security Updates"
              - "Connectors"
              - "Definition Updates"
              - "Update Rollups"
              - "Updates"
              - "Guidance"
              - "Application"
              - "Tools"
              - "Service Packs"
              - UpdateRollups
              - Tools
              - Application
              - "Windows Server 2016"
              - "Windows Server 2019"
              - Updates
              - "Drivers"
            #log_path: C:\Crombeen\Logs\win_updates.log
            reboot: "{{ rebt }}"
            state: installed
            #        use_scheduled_task: no # not required. 
            # Will not auto elevate the remote process with I(become) and use a scheduled task instead.
            # ,Set this to C(yes) when using this module with async on Server 2008, 2008 R2, or Windows 7, or on Server 2008 that is not authenticated with basic or credssp.,Can also be set to C(yes) on newer hosts where become does not work due to further privilege restrictions from the OS defaults.
          when: 
            - ansible_facts['os_family'] == "Windows"
      rescue:        
        - name: restart windows
          win_shell: "restart-computer -Force"
          when:
            - ansible_facts['os_family'] == "Windows"
            - rebt
        - name: Run Install Task
          become: no
          win_updates:
            category_names:
              - "Critical Updates"
              - "CriticalUpdates"
              - "Feature Packs"
              - "Security Updates"
              - "Connectors"
              - "Definition Updates"
              - "Update Rollups"
              - "Updates"
              - "Guidance"
              - "Application"
              - "Tools"
              - "Service Packs"
              - UpdateRollups
              - Tools
              - Application
              - "Windows Server 2016"
              - "Windows Server 2019"
              - Updates
              - "Drivers"
            #log_path: C:\Crombeen\Logs\win_updates.log
            reboot: "{{ rebt }}"
            state: installed
            #        use_scheduled_task: no # not required. 
            # Will not auto elevate the remote process with I(become) and use a scheduled task instead.
            # ,Set this to C(yes) when using this module with async on Server 2008, 2008 R2, or Windows 7, or on Server 2008 that is not authenticated with basic or credssp.,Can also be set to C(yes) on newer hosts where become does not work due to further privilege restrictions from the OS defaults.
          when: 
            - ansible_facts['os_family'] == "Windows"
