---
galaxy_info:
  role_name: server-update-reboot
  author: Ryan Daniels
  description: Role to update packages on linux and optionally reboot
  license: MIT
  min_ansible_version: 2.7.1
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - system
    - update

dependencies: []
