- name: Stop Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Stop virtual machine
      azure_rm_virtualmachine:
        resource_group: azure_prox1
        name: azure_prox1
        allocated: no