- hosts: lab
  gather_facts: no
  tasks:
  - name: Test system connection
    wait_for_connection:
      timeout: 20
    tags: software

  - name: Clean chocolatey/nuget cache
    win_file:
      path: '{{ item }}'
      state: absent
    with_items:
    - '%UserProfile%\AppData\Local\Temp\chocolatey\'
    - '%UserProfile%\AppData\Local\Temp\nuget\'
    - '%UserProfile%\AppData\Local\NuGet\Cache\'
    tags: cache

  - name: cleanup leftover user files
    win_file:
      path: '{{ item }}'
      state: absent
    with_items:
    - '%UserProfile%\Downloads\'
    - '%UserProfile%\Desktop\'