- hosts: all
  vars:
      - diag: "{{ install_diagnostics | False }}"
  become: sudo
  tasks:
  - name: make sure useful utilities are present
    package:
      name:
        - ncdu
        - mlocate
        - htop
        - curl
        - iotop
        - virt-what
        - net-tools
        - ethtool
        - ssh
        - bing
        - vtprint
        - mtr-tiny
        - sudo
        - sysstat
        - zip
        - unzip
        - vim
        - iftop
        - htop
        - curl
        - nano
        - less
        - ntp
        - grepcidr
        - netmask
        - pwgen
        - rsync
        - sipcalc
        - smartmontools
        - minicom
        - bzip2
        - buffer
        - screen
        - whois
        - iperf
        - pv
      # - molly-guard

      state: present

  - name: make sure useful utilities are present
    when: ansible_facts['os_family'] == "RedHat"
    package:
      name:
        - 'bash-completion-extras'
        - multitail

  - name: diagnostic tools
    when: diag
    package:
      name:
        - tshark

