- hosts: all

  become: sudo
  tasks:
  - name: make sure useful utilities are present
    package:
      name:
        - ncdu
        - mlocate
        - htop
        - curl
        - iotop
        - virt-what
        # - molly-guard
        - net-tools
        - ethtool
        - ssh
        - bing
        - vtprint
        - mtr-tiny
        - sudo
        - sysstat
        - zip
        - unzip
        - vim
        - iftop
        - htop
        - multitail
        - curl
        - nano
        - less
        - ntp
        - grepcidr
        - tshark
        - netmask
        - pwgen
        - rsync
        - sipcalc
        - smartmontools
        - minicom
        - bzip2
        - buffer
        - screen
        - whois
        - iperf
        - pv
      state: present

  - name: make sure useful utilities are present
    when: ansible_facts['os_family'] == "RedHat"
    package:
      name:
        - 'bash-completion-extras'
