- hosts: all
  ignore_unreachable: False
  gather_facts: yes
  vars:
    - rebt: "{{ reboot_now | default('false') }}"
  tasks:
    - name: update Debian based
      become: yes
      when: ansible_facts['os_family'] == "Debian"
      block:
        - name: Update apt repo and cache on all Debian/Ubuntu boxes
          apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

        - name: Upgrade all packages on servers
          apt: upgrade=dist force_apt_get=yes

        - name: Check if a reboot is needed on all servers
          register: reboot_required_file
          stat: path=/var/run/reboot-required get_md5=no

        - name: Reboot the box if kernel updated
          reboot:
            msg: "Reboot initiated by Ansible for kernel updates"
            connect_timeout: 5
            reboot_timeout: 300
            pre_reboot_delay: 0
            post_reboot_delay: 30
            test_command: uptime
          when: reboot_required_file.stat.exists

    - name: update system (RedHat)
      become: yes
      become_method: sudo
      yum:
          update_cache: yes # not required. Force yum to check if cache is out of date and redownload if needed. Has an effect only if state is I(present) or I(latest).
          name: '*'
          state: latest
      when: ansible_facts['os_family'] == "RedHat"

    - name: reboot linux if reboot_now is true
      become: yes
      become_method: sudo
      reboot:
          post_reboot_delay: 15 # not required. Seconds to wait after the reboot was successful and the connection was re-established.,This is useful if you want wait for something to settle despite your connection already working.
          test_command: whoami # not required. Command to run on the rebooted host and expect success from to determine the machine is ready for further tasks.
          reboot_timeout: 600 # not required. Maximum seconds to wait for machine to reboot and respond to a test command.,This timeout is evaluated separately for both network connection and test command success so the maximum execution time for the module is twice this amount.
          msg: Reboot initiated by Ansible # not required. Message to display to users before reboot.
          connect_timeout: undefined # not required. Maximum seconds to wait for a successful connection to the managed hosts before trying again.,If unspecified, the default setting for the underlying connection plugin is used.
      when:
        - rebt == true