- hosts: all
  tasks:

  - name: Disable Autologon, change registry key
    win_regedit:
       path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon
       name: AutoAdminLogon
       data: 0
