- hosts: all
  tasks:

  - name: Warn logged in users of impending upgrade (note use of async to stop the module from waiting until notification expires).
    win_toast:
     expire: 60
     title: System Upgrade Notification
     msg: Automated upgrade about to start.  Please save your work and log off before
    async: 60
    poll: 0
    become: yes