- hosts: all
  strategy: free
  tasks:
  - name: ensure Chocolatey itself is installed and use internal repo as source
    win_chocolatey:
      name: chocolatey
      source: https://iis_host1.cforat.org/chocolatey

  - name: chocolatey feature config
    win_chocolatey_feature:
       name: useRememberedArgumentsForUpgrades # required. The name of the feature to manage.,Run C(choco.exe feature list) to get a list of features that can be managed.
       state: enabled # not required. choices: disabled;enabled. When C(disabled) then the feature will be disabled.,When C(enabled) then the feature will be enabled.


  - name: install foxit args                                        
    win_chocolatey:
      name: foxitreader
      install_args: "/LANG=en"
      state: latest
      source: https://iis_host1.cforat.org/chocolatey

  - name: xmind
    win_chocolatey:
      name: xmind
      state: latest

 

  - name: install vlc player from internal with args
    win_chocolatey:
      name: vlc
      install_args: "/Language:en"
      state: latest                                    
      source: https://iis_host1.cforat.org/chocolatey

  - name: install other packages that don't require extra args
    win_chocolatey:
      name: googlechrome,firefox,sysinternals
      state: latest                                    
      source: https://iis_host1.cforat.org/chocolatey

  - name: update packages from internal
    win_chocolatey:
      name: all
      state: latest

